### ISSUE TITLE
Challah breaks shoulda/matchers uniqueness?

### ISSUE THREAD

**Issue by thewatts** [jdtornow/challah#29]
#### Context:
[my comment](https://github.com/thoughtbot/shoulda-matchers/issues/935#issuecomment-238006085) and subsequent comments and [pip's comment](https://github.com/thoughtbot/shoulda-matchers/issues/935#issuecomment-238258856)

#### Background:
For some reason - `shoulda/matchers` validation of uniqueness is failing (just in specs) when `challah` is included in a project.

#### Example App:
https://github.com/thewatts/uniqueness

( models provided are `User` and `Trait` )

##### To Reproduce:
`clone`, `bundle`, db creation/migration, etc

run: `bundle exec rspec spec` -> all tests will pass.

Add `challah` to `Gemfile` and bundle.

run: `bundle exec rspec spec` -> uniqueness specs fail.

<details>
  <summary> Failing Specs Details</summary>
```
.F..F

Failures:

  1) Trait should validate that :color is case-sensitively unique
     Failure/Error: it { should validate_uniqueness_of :color }
       Trait did not properly validate that :color is case-sensitively unique.
         After taking the given Trait, whose :color is ‹"red-2"›, and saving it
         as the existing record, then making a new Trait and setting its :color
         to ‹"red-2"› as well, the matcher expected the new Trait to be
         invalid, but it was valid instead.
     # ./spec/models/trait_spec.rb:7:in `block (2 levels) in <top (required)>'

  2) User should validate that :email is case-sensitively unique
     Failure/Error: it { should validate_uniqueness_of :email }
       User did not properly validate that :email is case-sensitively unique.
         After taking the given User, whose :email is ‹"user-3@example.com"›,
         and saving it as the existing record, then making a new User and
         setting its :email to ‹"user-3@example.com"› as well, the matcher
         expected the new User to be invalid, but it was valid instead.
     # ./spec/models/user_spec.rb:8:in `block (2 levels) in <top (required)>'

Finished in 0.06393 seconds (files took 1.51 seconds to load)
5 examples, 2 failures

Failed examples:

rspec ./spec/models/trait_spec.rb:7 # Trait should validate that :color is case-sensitively unique
rspec ./spec/models/user_spec.rb:8 # User should validate that :email is case-sensitively unique
```
</details>

---

Looks like @philtr just added an issue as well, #28

**Comment by thewatts** [comment]
closing in favor of comment on #28
